language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: PJkk+/EIqUeo71mxAZzssIMPOapcYppJdNPXfEXnK26gXobFodVBUqFiF57+QSE+RSvokF00IGtlj/vwXRcShYSEbp7camxuRqIXJGvb+fclT4zgwW9BmBRF+RKYx3S74NRu4FNJM/RavM1Cy/pcdT/ZRhFxRJyiK79Z2+8q2BITT/XrnQbg14bv9Mj7Nl6TLP4/PxqkY4KNrnNgBkXNlQTO2J6Pl6TEcA0Qoxb9PdS1E7jbkhfkaPVnd788m3HcBgjYU7OV4x2ZQEdLhs+u5lAeHBCAn/ACdMvHJgRe9np/9ByS2vbVbHc33CEX8cKsm6UYIxe6B9OOo+c/kM1/FsxyndgLlD95lwqxnJXuPMzLF0FwGJ+ycHTDm7eCMaEmEEt2qOBKuFvePmL3orJVGsHB+P/nDKaOZW0tyUaZSeWZ604FrFPfx1njaOdOJueD0tSxdt4Vx14lQss1rdd2vLV0mWZs0em5QA89nRpHt+M8k8vNB7CozTD+T8RqjXp9uBRryVlfwroa7yS021Tswx9/PHPVC4BwYcP8rRad/HPkXc+JECp/RPOYOWNKS/WNYJGfIWQwUsmN3f24nzBbXZTfKV5PS97tAgNmMGSxj6hG0W34yDPWp6uq6lb4FZgDXYAVb7yBJMW1V4ErOLtwqsaqz0MCi92mIv/DD+GU8jE=
  - secure: gEpOawiw8BU8u0xvK1egvFOfKrpQ6Su7xunOUVu89EHrJrX1gbMdifSjm+zNLaqh72pyCNrx3IXfLznPnxxUx9oKUHjApHgk5baO6+KUgl4DoNHtnmvYcMRVCAsmsh4yvLm+MfQENUw4MnZbmsL/+4tvE65Cg7J2koNNLq2U6Tniu0Gh2CLa5Vin/X8ttDmx8ylyuaoChxMRtkuTRexmXYJQCsmq+yjDXdnOUuOA2EwjovOA3jHY5zy+lZWJE0mHDAPeY6iUjVc242OVg0jjZfoQTjLPvuBg1ib36Vt91Bs7HbGBxkzxdraYTb9I1cnDaNGGHiHSIBCm0Ns26/6RarZ7AraX/xD3indt39jtB1lsYto5oWdOxue1zDsmPzc6u1UJ2g0L730PlR2hgpoeqfrvWuet0XCeWGRhIZkHerAjdYmwNog9UyrMphaVKbMeg22+z0+u4BB+8KI04XL/rT9GsF0Mk4PmtnYmWVr0lqf6pX6gs9i+hp62YclZI46K2bSlk5fyaLn70fxwuNXEypqFc2aPywK7+MoLharSTctO4ajcpVE5p2pIwTwnE4TDTI4HqU5Q0N8z0OZLtaG9+HmSKCEeqVy3xJPSC6mNY+pJnA1glwWsAOvEEGOjZ7F+prnyFcKXP67AXH0jHjp7tjTK1ZXOukqqS0ulQS5KBEQ=
