language: go
install:
#- go get -v[github.com/spf13/hugo]
# go get -v[https://github.com/gohugoio/hugo]
go get -v[github.com/gohugoio/hugo]
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: GWfwPJj3e0OpumzYOi4F9LK+rtuCAqQdcQT8zt3rAuqGdX5oo3yu4BCkzuunF71xXCe2Ggxbn6aXKsFz2paiCIFOmi12+FnHFIIpUGbQzoBmhb811Cfbi1PIiiiVqzItxnm+27Wzjnk52BkOfYsj/IohShou9Zn+FDvoanp0jbCyAhQMRzOD6hBdbdcmlREsUyx0VvJl6EKfD9LwkuAarOW2+nuW0/NPsK+CrniZ/FsJpomEvjMi80EBRpugdvA0BE22gbHrvBP3ZDdxCtnh6yHNnwyG116SlMoK1blgqfxUw6mBeCvpGFnxGuwQr8nRRjJ2iEBx95zEPn927Zot5ip/lmDm+E7WTdk9lzv9SgXL3B6GE0W+4bhcvY9O31FHwqoXKm49kpeaJztOJD79aYEy6UBlVuGqrq0Qa9ScqJ8d31esOX0UbcRRffnsKvFSDixn98xMIiJaroPawDFourSf7PmB1YaaCfGIef8Q9/wATDWB1NlpZmtBF3F4OfgkUte9cKdu11Hv1JB0ohO2GrGVAHudQjGGISBi1LzTFtm11oqDfxxtXTj5UghqYTdpW6khX3yQVK2fKvKxmT4vOWsP5KdEJK94jjeK9wcZtgUl42wEQEmMD1udWxGEJYV5/adWW4im4qbpH78O3lRn/59NWtVe8vSQfdiPGUmJXyU=
  - secure: mxusk5pnPmD/oZTD4qo3md0T2sbJJnO5FZbCL7iizguW1idZRljJTI1+M0fEqYHBgWbXJkkfUh89+vdv8JPTUbFPzYI2uhGVYdH9dtYugkS7AV3rc3qEWViCHMkIb2CD0HPOJFOHUW+GoeFfCrwFlMUW4vQOoCYsfjkpc0Xp5FBM8/H3l3Jz9erOROW5lGlj5ZTXa31f6beeTeX4lWiPTQawY/QLJk7LZt79klHMrWHFiSCeF0ysDrjwVvKa5FxqYVlIhXJ/KGMyscVGFftvld+LyKywz+KCQNQYvk5lWmW3ZYSb6Z8AI0jJJNzNVQoWJ2vulA7jYHepPGLu13GOWw9AEsX9r3ewDiPuQYxzGOeJAThfJvUIk2gtYqL7qsL7xuKGO0m7VyzQDOI7St6fCk8Yv8fLHySXktU5+rPJCYuuOz+Kl0LShOC+MgBcdKo9GddxRnc05mJaVr1WHXy2P5WZEbW9bQeGF3Ol7FbS6X+2BCK05QCzPov1qC2EkeE43SH8XgXf7tXb1s9MqLqdGoQhlwmMTd8H2B2Nqa+mBFClcAEk6TYZYVocQnf0SxABz7XRteRwi5KsDBQOvCYA+4VDovEl4VSitH8zmvWpBP8ZLzKHo+rlxUxv6B8rbLzojuF3WP17wsQuHl88FkbvCtEtF9xR8xLyJ0gNSJr2Q+s=
