language: go
install:
#- go get -v github.com/gohugoio/hugo
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: U+HgggB7OI8jTE/Hzz+P38rMZChNxUiWvv6XJGonQilfI7yJbx6rro4E0rp8JlC96CSHeYpbNivx6AW79vFdBpOH/PqYK3e15Z8GIB4JCloy8SCxAOfeCK2H9tgJc/uTn4/Fuko6MROEosXF00MVNAmlgCMXFNyXDYQ44IQG+lAwfm7dI+VC8Lrj0tWc/XK85655WjEXjlFcom1TVj6D8yQ8hHEsZBHkJnrEl2fEvHz7XhRGb0locaZ+CDaSMCnQScSIzuBtAHH3h1r0i26CKxIH00CbOP0ODGG2bJolRYjspTL1Q5IAFpMGe2M7WzgEQitGxlA+8Vy/7JvEhtXZufHvK5B8q6whGitNWGa0oZ6Y5Rzlg4abmc4G+4FYinr2gNkg3YL9qP9CCXbOhb45qaNOLR1hUSURup6m77lJSr+p0AxCK1dsfNlyeAjcLVqk33Fc+KmRAE/69kwpKCxIc8RUUqUpxCQ9WcS6fjp13bmesZmbq0o7ZDt/NI7s7s3eZAZ6dA4Mk4o0SLRbrmOwIIi72jnpwJhSlbpg1JPTTev/gnfiD6xdzdofCwoxrtim5zFrgLJAx8qqheW0FgE3AXaGxk9hkfK07PjQkLOFKMQcSa5cvoGmsCQGigEX/R0I47GJx86gPMIjh1nr4nvWOaAliN5l+lIpxSeFhRLujFY=
  - secure: cC30rWUKR7WWvqGaD8mDdj5JbT0BgqR0XcFo+M21HxHRSNO6aS02+ufT3GIDuAZ7tzL/f0Ld6SLMJks2qcF9e7Gtc+035+2+jF4VLRCjYVfK108YiUX3bRKpTwQai4ipPOZecX0uUOyWZ/oXktxKGc+uu7jiFs7Y9hrVcHnPqraM9M072I3dqPm4PZBJBokU/LXFAjRQFPfT6ktjiKRvwEiP5V7ZgtvHMgNkjpoAPflUDq3QBv0AmS+oiBjr5THE8O5h6kIU96kDntS+63B4jpxjT2RVKX8gu6oShtQOn2iIGX1da6EhFunjcM1ZXNmlN6uXyLboI9RYPLflmBkMt3Sh/wFMJJIEBW8ZZkAaXYpIN5Vlh9fJedFS08NAcpBJYB0vZ4M7DEpJ+QwP7q0zSpLbeoClDUHJfiiG/WGz0I06FePYLDa4WAO/1Q7Xw7oihC3ZSspFcR8FaQOwVOVwFiCQiUb8wYNPipMJ1vw0TRg6GrqsN3HbA2ROqbsQQ7Fa2g6lFrRrJQ1MVyGOkM08QizxLmF5Y25MutEArAcDMXc3WR/SvSkI7oeMzl3Sy/B/1OAnopbt07Ren3rMcVzqpvN24XF1Xi4wqZnSXRQ5ctebE8LeN3FM5sRvpB+YAgxNwh9AJyMBTjFhEAzhQU755vkrK+8GF7HNqxKktTnO3XY=
